<?php

declare(strict_types=1);

namespace Bitrix\Disk\Document\Vibeoffice;

use Bitrix\Disk\Document\Models\DocumentService;
use Bitrix\Disk\Document\Models\DocumentSession;
use Bitrix\Disk\Document\Models\DocumentSessionTable;
use Bitrix\Disk\Document\SessionManager;
use Bitrix\Main\Application;
use Bitrix\Main\Web\Json;

/**
 * Session manager for the vibeoffice platform (P4.T1).
 *
 * vibeoffice sessions are written to the shared `b_disk_document_session` table with
 * `SERVICE='vibeoffice'` through this {@see SessionManager} subclass — exactly the
 * pattern OnlyOffice uses ({@see \Bitrix\Disk\Document\OnlyOffice\DocumentSessionManager}).
 * No new session table is introduced (ADR §3/§4, rejected variant C); `SERVICE` already
 * exists in the model, so no schema migration is needed.
 *
 * `EXTERNAL_HASH` of the session is the `host_doc_key` the platform receives as `{docKey}`
 * in `/v1` paths (it is auto-generated by {@see DocumentSessionTable::generateDocumentKey()}).
 *
 * vo-specific runtime metadata (the platform `session_id`, the last `editor_key`, `rev`)
 * is NOT given its own table either: it is merged under a reserved `vo` key into the
 * session `CONTEXT` JSON (Q-3). The base {@see \Bitrix\Disk\Document\Models\DocumentSessionContext}
 * keys (`objectId`/`attachedObjectId`/`externalLinkId`) are preserved untouched, so the
 * model's rights checks (`canEdit`/`canRead`, which rebuild the context from CONTEXT) keep
 * working — `DocumentSessionContext::buildFromJson()` simply ignores the extra `vo` key.
 */
final class DocumentSessionManager extends SessionManager
{
	/** Reserved CONTEXT key carrying the vo-specific runtime metadata. */
	public const CONTEXT_VO_KEY = 'vo';

	/** Named application lock prefix serialising the CONTEXT read-modify-write (M1). */
	private const CONTEXT_LOCK_PREFIX = 'disk_vo_session_ctx_';

	/** Seconds to wait for the per-session CONTEXT lock before falling back to best-effort. */
	private const CONTEXT_LOCK_TIMEOUT = 5;

	/**
	 * Sub-key (inside {@see self::CONTEXT_VO_KEY}) carrying the file `GLOBAL_CONTENT_VERSION`
	 * captured when the session was created. {@see DocumentSession::isOutdatedByFileContent()}
	 * reads it (via {@see DocumentSession::getContentVersionSnapshot()}) to rotate the docKey
	 * of a stale VIEW session by monotonic content version instead of a second-granular
	 * timestamp. Written only here, so non-vibeoffice sessions keep the legacy timestamp check.
	 */
	public const CONTEXT_VO_CONTENT_VERSION_KEY = 'contentVersion';

	/**
	 * Sub-key (inside {@see self::CONTEXT_VO_KEY}) carrying the editor visual mode
	 * ({@see \Bitrix\Disk\Document\OnlyOffice\Editor\ConfigBuilder::VISUAL_MODE_USUAL} /
	 * {@see \Bitrix\Disk\Document\OnlyOffice\Editor\ConfigBuilder::VISUAL_MODE_COMPACT}) requested
	 * when the session was opened. The config channel resolves the session by hash alone (the
	 * editorMode of the load* action never reaches it directly), so it is persisted here and read
	 * back in {@see \Bitrix\Disk\Controller\Vibeoffice::buildOpenBody()} to inject `editor.ui.mode`.
	 * Written only for a compact open (messenger-call point #4); its absence means the full editor.
	 */
	public const CONTEXT_VO_EDITOR_MODE_KEY = 'editorMode';

	protected DocumentService|null $service = DocumentService::Vibeoffice;

	protected function buildFields(): array
	{
		$fields = parent::buildFields();
		$fields['TYPE'] = $this->sessionType;

		return $fields;
	}

	/**
	 * Stamps the newly created session with the current file `GLOBAL_CONTENT_VERSION`
	 * snapshot (under `CONTEXT.vo.contentVersion`).
	 *
	 * This covers BOTH the first open (initial create) AND the outdated-rotation path
	 * in {@see SessionManager::findOrCreateSession()} (which calls `addSession()` again
	 * when a VIEW session is stale), so a freshly rotated VIEW session always records the
	 * up-to-date content version and does not immediately re-trigger rotation.
	 *
	 * Best-effort: a failed stamp must not fail session creation. Without the snapshot the
	 * model simply falls back to the legacy timestamp staleness check.
	 */
	public function addSession(): ?DocumentSession
	{
		$session = parent::addSession();
		if ($session)
		{
			$this->persistContentVersionSnapshot($session);
		}

		return $session;
	}

	/**
	 * Persists the current file `GLOBAL_CONTENT_VERSION` into `CONTEXT.vo.contentVersion`
	 * (merged over any existing vo-metadata, leaving the base context keys untouched).
	 */
	public function persistContentVersionSnapshot(DocumentSession $documentSession): bool
	{
		$contentVersion = $this->resolveContentVersion();
		if ($contentVersion === null)
		{
			return false;
		}

		return $this->persistSessionMetadata($documentSession, [
			self::CONTEXT_VO_CONTENT_VERSION_KEY => $contentVersion,
		]);
	}

	/**
	 * Current monotonic content version of the live file the session points at.
	 *
	 * Deliberately NOT set for a version-pinned session ({@see DocumentSession::isVersion()}):
	 * such a view streams a fixed historical version, while
	 * {@see DocumentSession::isOutdatedByFileContent()} compares against the live file's
	 * version — stamping it would rotate the docKey on every open as soon as the live file
	 * moves ahead. Version-pinned sessions therefore keep the legacy timestamp check
	 * (which never rotates them either).
	 *
	 * The live file is resolved from {@see SessionManager::$file} when an explicit file was
	 * set, but the typical Disk path (CRM/comments/activity stream) opens a document through
	 * an {@see \Bitrix\Disk\AttachedObject} and leaves `$this->file` null (the controller
	 * calls `setFile($object)` with a null `$object`, resolving the real file as
	 * `$attachedObject->getFile()`). In that case we fall back to the attached object's live
	 * file ({@see \Bitrix\Disk\AttachedObject::getFile()} returns the underlying
	 * {@see \Bitrix\Disk\File} or null), so attachedObject-opened VIEW sessions also get the
	 * content-version snapshot. Returns null when no live file is available (best-effort).
	 */
	private function resolveContentVersion(): ?int
	{
		if ($this->version)
		{
			return null;
		}

		$file = $this->file ?: $this->attachedObject?->getFile();
		if ($file)
		{
			return (int)$file->getGlobalContentVersion();
		}

		return null;
	}

	/**
	 * Persists the minimal vo-metadata subset host needs to re-issue the config and to
	 * drain (Q-3): the platform `session_id`, the last `editor_key`, `rev`. Stored under
	 * the reserved {@see self::CONTEXT_VO_KEY} sub-key of the session CONTEXT JSON, merged
	 * over any previously stored vo-metadata, alongside (never overwriting) the base
	 * DocumentSessionContext keys.
	 *
	 * Failover/refresh itself is driven by the frontend helper over SSE; the host only
	 * keeps what it needs to resolve `refresh_url`/re-open and for drain.
	 *
	 * @param array<string, mixed> $metadata e.g. ['session_id' => …, 'editor_key' => …, 'rev' => …]
	 */
	public function persistSessionMetadata(DocumentSession $documentSession, array $metadata): bool
	{
		$metadata = array_filter($metadata, static fn($value) => $value !== null);
		$sessionId = (int)$documentSession->getId();
		if (!$sessionId || empty($metadata))
		{
			return false;
		}

		// Serialise the CONTEXT read-modify-write against a concurrent writer (an `open`
		// persisting session_id/rev vs a `document.failover` webhook persisting editor_key) so
		// the vo-metadata merge does not lose an update (M1). The lock is keyed by the session id
		// and the freshest CONTEXT is re-read from the DB inside the critical section; if the lock
		// cannot be taken we still proceed best-effort on the re-read (a narrowed race window).
		$connection = Application::getConnection();
		$lockName = self::CONTEXT_LOCK_PREFIX . $sessionId;
		$locked = $connection->lock($lockName, self::CONTEXT_LOCK_TIMEOUT);

		try
		{
			$rawContext = $this->readFreshContextRaw($sessionId) ?? $documentSession->getContextRaw();
			$context = $this->decodeContext($rawContext);

			$existingVo = is_array($context[self::CONTEXT_VO_KEY] ?? null) ? $context[self::CONTEXT_VO_KEY] : [];
			$context[self::CONTEXT_VO_KEY] = array_merge($existingVo, $metadata);

			$result = DocumentSessionTable::update($sessionId, [
				'CONTEXT' => Json::encode($context),
			]);

			return $result->isSuccess();
		}
		finally
		{
			if ($locked)
			{
				$connection->unlock($lockName);
			}
		}
	}

	/**
	 * Re-reads the freshest CONTEXT JSON straight from the DB (bypassing any model-level cache)
	 * so the merge in {@see self::persistSessionMetadata()} runs on the latest stored value.
	 */
	private function readFreshContextRaw(int $sessionId): ?string
	{
		$row = DocumentSessionTable::getRow([
			'select' => ['CONTEXT'],
			'filter' => ['=ID' => $sessionId],
		]);

		$context = $row['CONTEXT'] ?? null;

		return is_string($context) ? $context : null;
	}

	/**
	 * Reads the vo-metadata subset previously stored by {@see self::persistSessionMetadata()}.
	 *
	 * @return array<string, mixed>
	 */
	public static function extractVoMetadata(DocumentSession $documentSession): array
	{
		$context = self::decodeContext($documentSession->getContextRaw());

		$vo = $context[self::CONTEXT_VO_KEY] ?? null;

		return is_array($vo) ? $vo : [];
	}

	/**
	 * Decodes the session CONTEXT JSON into an array. Returns an empty array when the raw
	 * value is null/empty, the JSON is invalid, or it does not decode to an array.
	 *
	 * @return array<string, mixed>
	 */
	private static function decodeContext(?string $raw): array
	{
		if ($raw === null || $raw === '')
		{
			return [];
		}

		try
		{
			$decoded = Json::decode($raw);
		}
		catch (\Throwable)
		{
			return [];
		}

		return is_array($decoded) ? $decoded : [];
	}
}
