<?php

declare(strict_types=1);

namespace Bitrix\Im\V2\Message\BlocksBuilder;

use Bitrix\Im\V2\Error;

class BuilderError extends Error
{
	public const BLOCK_NOT_AVAILABLE = 'BLOCK_NOT_AVAILABLE';
	public const BLOCK_LENGTH_EXCEEDED = 'BLOCK_LENGTH_EXCEEDED';
	public const EMPTY_REQUIRED_FIELD = 'EMPTY_REQUIRED_FIELD';
	public const INVALID_ELEMENTS = 'INVALID_ELEMENTS';
	public const EMPTY_ELEMENTS = 'EMPTY_ELEMENTS';
	public const INVALID_ELEMENTS_FIELD = 'INVALID_ELEMENTS_FIELD';
	public const EMPTY_ELEMENTS_FIELD = 'EMPTY_ELEMENTS_FIELD';
	public const WRONG_ELEMENT_TYPE = 'WRONG_ELEMENT_TYPE';
	public const INVALID_IMAGE_URL_FIELD = 'INVALID_IMAGE_URL_FIELD';
	public const INVALID_ROWS_FIELD = 'INVALID_ROWS_FIELD';
	public const EMPTY_ROWS_FIELD = 'EMPTY_ROWS_FIELD';
	public const INVALID_SIZE_FIELD = 'INVALID_SIZE_FIELD';
	public const INVALID_STATUS_FIELD = 'INVALID_STATUS_FIELD';
	public const INVALID_TEXT_FIELD = 'INVALID_TEXT_FIELD';
	public const EMPTY_TEXT_FIELD = 'EMPTY_TEXT_FIELD';
	public const INVALID_TYPE_FIELD = 'INVALID_TYPE_FIELD';
	public const INVALID_CONFIG = 'INVALID_CONFIG';
	public const MAX_COLUMN_COUNT = 'MAX_COLUMN_COUNT';
	public const BLOCK_NOT_FOUND = 'BLOCK_NOT_FOUND';
	public const ELEMENT_NOT_FOUND = 'ELEMENT_NOT_FOUND';
	public const INVALID_TITLE_FIELD = 'INVALID_TITLE_FIELD';
	public const EMPTY_TITLE_FIELD = 'EMPTY_TITLE_FIELD';
	public const INVALID_SOURCES_FIELD = 'INVALID_SOURCES_FIELD';
	public const INVALID_URL_FIELD = 'INVALID_URL_FIELD';
	public const EMPTY_URL_FIELD = 'EMPTY_URL_FIELD';
	public const INVALID_CODE_SOURCES = 'INVALID_CODE_SOURCES';
	public const EMPTY_IMAGE_URL_FIELD = 'EMPTY_IMAGE_URL_FIELD';
	public const INVALID_BUTTONS_FIELD = 'INVALID_BUTTONS_FIELD';
	public const INVALID_BUTTON_FIELD = 'INVALID_BUTTON_FIELD';
	public const WRONG_BUTTON_TYPE = 'WRONG_BUTTON_TYPE';
	public const INVALID_ACTION_ID_FIELD = 'INVALID_ACTION_ID_FIELD';
	public const EMPTY_ACTION_ID_FIELD = 'EMPTY_ACTION_ID_FIELD';
	public const INVALID_FILE_IDS_FIELD = 'INVALID_FILE_IDS_FIELD';
	public const EMPTY_FILE_IDS_FIELD = 'EMPTY_FILE_IDS_FIELD';
	public const GALLERY_ELEMENTS_EXCEEDED = 'GALLERY_ELEMENTS_EXCEEDED';
	public const GALLERY_FILES_NOT_AVAILABLE = 'GALLERY_FILES_NOT_AVAILABLE';
}
