<?php

declare(strict_types=1);

namespace Bitrix\Booking\Service;

use Bitrix\Booking\Entity\ExternalData\ItemType\CalendarEventItemType;
use Bitrix\Booking\Entity\Resource\ResourceCollection;
use Bitrix\Booking\Entity\Sku\SkuCollection;
use Bitrix\Booking\Internals\Container;
use Bitrix\Booking\Internals\Repository\BookingRepositoryInterface;
use Bitrix\Booking\Provider\Params\Booking\BookingFilter;
use Bitrix\Booking\Provider\Params\Booking\BookingSelect;
use Bitrix\Main\Localization\Loc;

class EventDescription
{
	private BookingRepositoryInterface $bookingRepository;

	public function __construct(
		private readonly string $languageId,
	)
	{
		$this->bookingRepository = Container::getBookingRepository();
	}

	public function getDescription(int $eventId): string
	{
		if (!$eventId)
		{
			return '';
		}

		$bookingsCollection = $this->bookingRepository->getList(
			filter: new BookingFilter([
				'EXTERNAL_DATA_ITEM' => (new CalendarEventItemType())->createItem()->setValue((string)$eventId),
			]),
			select: (new BookingSelect(['RESOURCES', 'SKUS']))->prepareSelect(),
		);
		$this->bookingRepository->withSkus($bookingsCollection);

		$booking = $bookingsCollection->getFirstCollectionItem();
		if (!$booking)
		{
			return '';
		}

		$resourcePart = $this->getResourceDescription($booking->getResourceCollection());
		$servicePart = $this->getServiceDescription($booking->getSkuCollection());

		$result = [];

		if ($resourcePart !== '')
		{
			$result[] = $resourcePart;
		}

		if ($servicePart !== '')
		{
			$result[] = $servicePart;
		}

		$bookingLine = Loc::getMessage(
			code: 'BOOKING_SERVICE_EVENT_DESCRIPTION_BOOKING',
			language: $this->languageId,
		);

		if ($bookingLine !== '')
		{
			$result[] = $bookingLine;
		}

		return implode(';' . PHP_EOL, $result);
	}

	public function clearOutFromDescription(string $description): string
	{
		if ($description === '')
		{
			return '';
		}

		// Remove lines generated by resource/services templates (by prefix)
		$patternsWithPlaceholders = [
			'BOOKING_SERVICE_EVENT_DESCRIPTION_RESOURCES_PATTERN',
			'BOOKING_SERVICE_EVENT_DESCRIPTION_SERVICES_PATTERN',
		];

		foreach ($patternsWithPlaceholders as $patternCode)
		{
			$patternPrefix = Loc::getMessage(code: $patternCode, language: $this->languageId);

			if ($patternPrefix === '')
			{
				continue;
			}

			// Match whole lines that START with this prefix.
			// Example: "^Resources: .*$" (multiline, case-insensitive)
			$pattern = '|^' . preg_quote($patternPrefix, '|') . '.*;[\r\n]*|im';
			$description = preg_replace($pattern, '', $description);
		}

		// Remove the "added by module" booking line
		$bookingMessage = Loc::getMessage(
			code: 'BOOKING_SERVICE_EVENT_DESCRIPTION_BOOKING',
			language: $this->languageId,
		);

		if ($bookingMessage !== '')
		{
			// Match whole line equal to this message
			$pattern = '|^' . preg_quote($bookingMessage, '|') . '$|im';
			$description = preg_replace($pattern, '', $description);
		}

		// Normalize: remove empty lines introduced by deletions, but keep other content as-is
		$lines = preg_split("/\r\n|\r|\n/", $description) ?: [];
		$lines = array_values(
			array_filter(
				$lines,
				static fn (string $line): bool => trim($line) !== ''
			)
		);

		return implode(PHP_EOL, $lines);
	}

	private function getResourceDescription(ResourceCollection $resourceCollection): string
	{
		if ($resourceCollection->isEmpty())
		{
			return '';
		}

		$resourceNames = [];
		foreach ($resourceCollection->getIterator() as $resource)
		{
			$resourceNames[] = $resource->getName();
		}

		return Loc::getMessage(
			code: 'BOOKING_SERVICE_EVENT_DESCRIPTION_RESOURCES',
			replace: [
				'#RESOURCES#' => implode(', ', $resourceNames),
			],
			language: $this->languageId,
		) ?: '';
	}

	private function getServiceDescription(SkuCollection $skuCollection): string
	{
		if ($skuCollection->isEmpty())
		{
			return '';
		}

		$skuNames = [];
		foreach ($skuCollection->getIterator() as $sku)
		{
			$skuNames[] = $sku->getName();
		}

		return Loc::getMessage(
			code: 'BOOKING_SERVICE_EVENT_DESCRIPTION_SERVICES',
			replace: [
				'#SERVICES#' => implode(', ', $skuNames),
			],
			language: $this->languageId,
		) ?: '';
	}
}
