<?php

declare(strict_types=1);

namespace Bitrix\Im\V2\SharingLink;

use Bitrix\Im\V2\Error;

class SharingLinkError extends Error
{
	public const
		NOT_FOUND = 'SHARING_LINK_NOT_FOUND',
		WRONG_PARAMS = 'SHARING_LINK_WRONG_PARAMS',
		UNIQUE_ALREADY_EXISTS = 'UNIQUE_SHARING_LINK_EXISTS',
		CREATION_ERROR = 'SHARING_LINK_CREATION_ERROR',
		WRONG_ENTITY  = 'SHARING_LINK_WRONG_ENTITY',
		ALREADY_REVOKED = 'SHARING_LINK_ALREADY_REVOKED',
		REVOKED = 'SHARING_LINK_REVOKED',
		ENTITY_NOT_FOUND = 'SHARING_LINK_ENTITY_NOT_FOUND',
		ACCESS_DENIED = 'SHARING_LINK_ACCESS_DENIED'
	;
}
