<?php
use Bitrix\Main\Loader;

Loader::registerClassAliases([
	'\Bitrix\Im\V2\Call\CallFactory' => '\Bitrix\Call\CallFactory',
	'\Bitrix\Im\Call\Registry' => '\Bitrix\Call\Call\Registry',
	'\Bitrix\Im\V2\Call\CallToken' => '\Bitrix\Im\V2\Integration\Call\CallToken',
	'\Bitrix\Im\Call\Signaling' => '\Bitrix\Call\Signaling',
	'\Bitrix\Im\Call\Util' => '\Bitrix\Call\Util',
	'\Bitrix\Im\Call\User' => '\Bitrix\Call\Rest\User',
	'\Bitrix\Im\Call\Auth' => '\Bitrix\Call\Rest\Auth',
	'\Bitrix\Im\Call\Conference' => '\Bitrix\Call\Conference',
	'\Bitrix\Im\Call\Background' => '\Bitrix\Call\Desktop\Background',
	'\Bitrix\Im\Call\Mask' => '\Bitrix\Call\Desktop\Mask',
	'\Bitrix\Im\Call\Integration\Zoom' => '\Bitrix\Im\Integration\Socialservices\Zoom',
	'\Bitrix\Im\Call\Integration\EntityType' => '\Bitrix\Call\Integration\EntityType',
	'\Bitrix\Im\Call\Integration\EntityFactory' => '\Bitrix\Call\Integration\EntityFactory',
	'\Bitrix\Im\Call\Integration\AbstractEntity' => '\Bitrix\Call\Integration\AbstractEntity',
	'\Bitrix\Im\Call\Integration\Chat' => '\Bitrix\Call\Integration\Chat',
	'\Bitrix\Im\Limit' => '\Bitrix\Call\Limit',
	'\Bitrix\Im\Call\CallUser' => '\Bitrix\Call\CallUser',
	'\Bitrix\Im\Call\Call' => '\Bitrix\Call\Call',
	'\Bitrix\Im\Call\VideoStrategyType' => '\Bitrix\Call\VideoStrategyType',
	'\Bitrix\Im\Model\CallTable' => '\Bitrix\Call\Model\CallTable',
	'\Bitrix\Im\Model\CallUserTable' => '\Bitrix\Call\Model\CallUserTable',
	'\Bitrix\Im\Model\ConferenceTable' => '\Bitrix\Call\Model\ConferenceTable',
	'\Bitrix\Im\Model\ConferenceUserRoleTable' => '\Bitrix\Call\Model\ConferenceUserRoleTable',
	'\Bitrix\Im\Controller\Call\Disk' => '\Bitrix\Call\Controller\Disk',
	'\Bitrix\Im\Controller\Call\Filter\Authorization' => '\Bitrix\Call\Controller\Filter\Authorization',
	'\Bitrix\Im\Controller\Call\Filter\DiskFolderAccessCheck' => '\Bitrix\Call\Controller\Filter\DiskFolderAccessCheck',
	'\Bitrix\Im\V2\Controller\Call\Background' => '\Bitrix\Call\Controller\Desktop\Background',
	'\Bitrix\Im\V2\Controller\Call\Mask' => '\Bitrix\Call\Controller\Desktop\Mask',
	'\Bitrix\Im\V2\Controller\Call' => '\Bitrix\Call\Controller\CallManager',
]);