<?php

declare(strict_types=1);

namespace Bitrix\Note\Internal\Model;

// EO_Collection can't be auto-generated by ORM\Loader because the name
// "EO_Collection" ends with "_Collection", which the loader misinterprets
// as a collection class for a nameless entity instead of an object class
// for the "Collection" entity.  Compile it explicitly.
\Bitrix\Main\ORM\Entity::compileObjectClass(CollectionTable::class);

class Collection extends EO_Collection
{
}
