<?php

namespace Bitrix\Crm\Feature;

use Bitrix\Crm\DbHelper;
use Bitrix\Main\Localization\Loc;

final class RepeatSaleSandbox extends BaseFeature
{
	public function getName(): string
	{
		return Loc::getMessage('CRM_FEATURE_REPEAT_SALE_SANDBOX_NAME');
	}

	public function getCategory(): Category\RepeatSale
	{
		return Category\RepeatSale::getInstance();
	}

	protected function getOptionName(): string
	{
		return 'allow_repeat_sale_sandbox_page';
	}

	public function getSort(): int
	{
		return 10;
	}

	public function enable(): void
	{
		if ($this->isEnabled())
		{
			return;
		}

		parent::enable();

		$this->createTable();
	}

	private function createTable(): void
	{
		$connection = \Bitrix\Main\Application::getConnection();
		$tableName = 'b_crm_repeat_sale_sandbox';

		if ($connection->isTableExists($tableName))
		{
			return;
		}

		DbHelper::queryByDbType(
			"CREATE TABLE IF NOT EXISTS $tableName ("
			. "ID INT NOT NULL AUTO_INCREMENT, "
			. "JOB_ID INT NOT NULL, "
			. "SEGMENT_ID INT, "
			. "ITEM_TYPE_ID INT NOT NULL, "
			. "ITEM_ID INT NOT NULL, "
			. "CLIENT_TYPE_ID INT, "
			. "CLIENT_ID INT, "
			. "CHECK_DATE DATE, "
			. "PROMPT TEXT, "
			. "PAYLOAD TEXT, "
			. "CREATED_AT DATETIME NOT NULL, "
			. "UPDATED_AT DATETIME NOT NULL, "
			. "PRIMARY KEY (ID)"
			. ")",
			"CREATE TABLE IF NOT EXISTS $tableName ("
			. "ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL, "
			. "JOB_ID int NOT NULL, "
			. "SEGMENT_ID int, "
			. "ITEM_TYPE_ID int NOT NULL, "
			. "ITEM_ID int NOT NULL, "
			. "CLIENT_TYPE_ID int, "
			. "CLIENT_ID int, "
			. "CHECK_DATE date, "
			. "PROMPT text, "
			. "PAYLOAD text, "
			. "CREATED_AT datetime NOT NULL, "
			. "UPDATED_AT datetime NOT NULL, "
			. "PRIMARY KEY (ID)"
			. ")"
		);
	}

	public function disable(): void
	{
		if (!$this->isEnabled())
		{
			return;
		}

		parent::disable();

		$this->dropTable();
	}

	private function dropTable(): void
	{
		$connection = \Bitrix\Main\Application::getConnection();
		$tableName = 'b_crm_repeat_sale_sandbox';

		if (!$connection->isTableExists($tableName))
		{
			return;
		}

		$connection->dropTable($tableName);
	}
}
