<?php

namespace Bitrix\Call\Track;

class TrackError extends \Bitrix\Call\Error
{
	public const
		EMPTY_DOWNLOAD_URL = 'EMPTY_DOWNLOAD_URL',
		DOWNLOAD_ERROR = 'DOWNLOAD_ERROR',
		SAVE_FILE_ERROR = 'SAVE_FILE_ERROR',
		DISK_ATTACH_ERROR = 'DISK_ATTACH_ERROR',
		TRACK_NOT_FOUND_ERROR = 'TRACK_NOT_FOUND_ERROR',
		TRACK_DUPLICATE_ERROR = 'TRACK_DUPLICATE_ERROR',
		FILE_SIZE_ZERO = 'FILE_SIZE_ZERO',
		FILE_SIZE_MISMATCH = 'FILE_SIZE_MISMATCH',
		PREVIEW_ALREADY_EXISTS = 'preview_already_exists',
		STATIC_PREVIEW_NOT_FOUND = 'static_preview_not_found',
		FILE_ARRAY_ERROR = 'file_array_error'
	;
}
