<?php
declare(strict_types=1);

namespace Bitrix\Landing\Metrika;

use Bitrix\Landing\Copilot\Generation;
use Bitrix\Landing\Copilot\Generation\Scenario\CreateSite;
use Bitrix\Landing\Copilot\Services\CreateAiSiteChecker;
use Bitrix\Landing\Site\Type;

/**
 * Detects the Metrika type of a site: AI-generated or built from a template.
 */
class SiteTypeResolver
{
	/**
	 * Site type of the online store scope. There is no constant for it in the module,
	 * the literal is taken from Tools::getBySiteType() / Categories::getBySiteType().
	 */
	private const SITE_TYPE_STORE = 'STORE';

	/**
	 * Per-request memoization of resolve(), keyed by site id.
	 * @var array<int, Types>
	 */
	private static array $typeCache = [];

	private CreateAiSiteChecker $createAiSiteChecker;

	public function __construct(?CreateAiSiteChecker $createAiSiteChecker = null)
	{
		$this->createAiSiteChecker = $createAiSiteChecker ?? new CreateAiSiteChecker();
	}

	public function resolve(int $siteId, string $siteType): Types
	{
		if ($siteId <= 0)
		{
			return Types::template;
		}

		if (isset(self::$typeCache[$siteId]))
		{
			return self::$typeCache[$siteId];
		}

		if (!$this->isPublicSitesScope($siteType))
		{
			self::$typeCache[$siteId] = Types::template;

			return self::$typeCache[$siteId];
		}

		try
		{
			$isAiSite = $this->createAiSiteChecker->isSiteCreated($siteId) || $this->hasLegacyGeneration($siteId);
		}
		catch (\Throwable)
		{
			// the type is resolved inside domain operations - the publication above all - and this is
			// the only place of the resolver that goes to the base: a failure of analytics must never
			// break the operation. The answer of a failed lookup is not cached, so the next call of the
			// request can still get the real one
			return Types::template;
		}

		self::$typeCache[$siteId] = $isAiSite ? Types::ai : Types::template;

		return self::$typeCache[$siteId];
	}

	public static function clearCache(?int $siteId = null): void
	{
		if ($siteId === null)
		{
			self::$typeCache = [];

			return;
		}

		unset(self::$typeCache[$siteId]);
	}

	/**
	 * Site is generated by the scenario that preceded AI 2.0.
	 */
	protected function hasLegacyGeneration(int $siteId): bool
	{
		return Generation::existsBySiteId($siteId, new CreateSite());
	}

	/**
	 * Only the regular sites scope can hold AI-generated sites.
	 */
	private function isPublicSitesScope(string $siteType): bool
	{
		return !in_array(
			$siteType,
			[
				self::SITE_TYPE_STORE,
				Type::SCOPE_CODE_KNOWLEDGE,
				Type::SCOPE_CODE_GROUP,
				Type::SCOPE_CODE_VIBE,
				Type::PSEUDO_SCOPE_CODE_FORMS,
			],
			true
		);
	}
}
