<?php

namespace Bitrix\Crm\Model\Dynamic;

use Bitrix\Crm\Field;
use Bitrix\Crm\Service\Container;
use Bitrix\Main\Application;
use Bitrix\Main\DI\ServiceLocator;
use Bitrix\Main\ORM\Data\DataManager;
use Bitrix\Main\ORM\Fields;
use CCrmFieldInfoAttr;

class RecurringTable extends DataManager
{
	public static function getTableName(): string
	{
		return 'b_crm_dynamic_recurring';
	}

	public static function getMap(): array
	{
		Container::getInstance()->getLocalization()->loadMessages();

		$fieldRepository = ServiceLocator::getInstance()->get('crm.model.fieldRepository');

		return [
			(new Fields\IntegerField('ID'))
				->configurePrimary()
				->configureAutocomplete(),
			(new Fields\IntegerField('ENTITY_TYPE_ID'))
				->configureRequired(),
			(new Fields\IntegerField('ITEM_ID'))
				->configureRequired(),
			new Fields\IntegerField('BASED_ID'),
			(new Fields\BooleanField('ACTIVE'))
				->configureDefaultValue('Y')
				->configureStorageValues('N', 'Y'),
			(new Fields\DateField('NEXT_EXECUTION'))
				->configureNullable()
			,
			(new Fields\DateField('LAST_EXECUTION'))
				->configureNullable()
			,
			(new Fields\StringField('IS_LIMIT'))
				->configureDefaultValue('N'),
			(new Fields\DateField('LIMIT_DATE'))
				->configureNullable()
			,
			new Fields\DateField('START_DATE'),
			(new Fields\IntegerField('LIMIT_REPEAT'))
				->configureNullable()
			,
			(new Fields\IntegerField('COUNTER_REPEAT'))
				->configureDefaultValue(0),
			(new Fields\IntegerField('CATEGORY_ID'))
				->configureNullable()
			,
			(new Fields\BooleanField('IS_SEND_EMAIL'))
				->configureDefaultValue('N')
				->configureStorageValues('N', 'Y')
			,
			(new Fields\ArrayField('EMAIL_IDS'))
				->configureNullable()
				->configureSerializationJson()
			,
			(new Fields\ArrayField('PARAMS'))
				->configureNullable()
				->configureSerializationJson()
			,
			$fieldRepository->getCreatedTime('CREATED_AT'),
			$fieldRepository->getUpdatedTime('UPDATED_AT'),
			$fieldRepository
				->getCreatedBy('CREATED_BY_ID')
				->configureDefaultValue(static fn() => Container::getInstance()->getContext()->getUserId())
			,
			$fieldRepository
				->getUpdatedBy('UPDATED_BY_ID')
				->configureDefaultValue(static fn() => Container::getInstance()->getContext()->getUserId())
			,
		];
	}

	public static function deleteByEntityTypeId(int $entityTypeId): void
	{
		$connection = Application::getConnection();
		$helper = $connection->getSqlHelper();

		$connection->query(sprintf(
			'DELETE FROM %s WHERE ENTITY_TYPE_ID = %d',
			$helper->quote(static::getTableName()),
			$helper->convertToDbInteger($entityTypeId),
		));

		self::cleanCache();
	}

	public static function getFieldsInfo(): array
	{
		$info = [];

		$info['ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
				CCrmFieldInfoAttr::AutoGenerated,
			],
		];
		$info['ENTITY_TYPE_ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::NotDisplayed,
				CCrmFieldInfoAttr::Required,
				CCrmFieldInfoAttr::Immutable,
			],
		];
		$info['ITEM_ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::NotDisplayed,
				CCrmFieldInfoAttr::Required,
				CCrmFieldInfoAttr::Immutable,
			],
		];
		$info['BASED_ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::NotDisplayed,
				CCrmFieldInfoAttr::Required,
				CCrmFieldInfoAttr::Immutable,
			],
		];
		$info['ACTIVE'] = [
			'TYPE' => Field::TYPE_BOOLEAN,
		];
		$info['NEXT_EXECUTION'] = [
			'TYPE' => Field::TYPE_DATE,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
			],
		];
		$info['LAST_EXECUTION'] = [
			'TYPE' => Field::TYPE_DATE,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
			],
		];
		$info['IS_LIMIT'] = [
			'TYPE' => Field::TYPE_BOOLEAN,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::Immutable,
				CCrmFieldInfoAttr::Required,
			],
		];
		$info['LIMIT_DATE'] = [
			'TYPE' => Field::TYPE_DATE,
		];
		$info['START_DATE'] = [
			'TYPE' => Field::TYPE_DATE,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::Immutable,
				CCrmFieldInfoAttr::Required,
			],
		];
		$info['COUNTER_REPEAT'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
			],
		];
		$info['CATEGORY_ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
		];
		$info['IS_SEND_EMAIL'] = [
			'TYPE' => Field::TYPE_BOOLEAN,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::CanNotBeEmptied,
			],
		];
		$info['EMAIL_IDS'] = [
			'TYPE' => Field::TYPE_TEXT,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
			],
		];
		$info['PARAMS'] = [
			'TYPE' => Field::TYPE_TEXT,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
			],
		];
		$info['CREATED_AT'] = [
			'TYPE' => Field::TYPE_DATETIME,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
				CCrmFieldInfoAttr::AutoGenerated,
			],
		];
		$info['UPDATED_AT'] = [
			'TYPE' => Field::TYPE_DATETIME,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
				CCrmFieldInfoAttr::AutoGenerated,
			],
		];
		$info['CREATED_BY_ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
				CCrmFieldInfoAttr::AutoGenerated,
			],
		];
		$info['UPDATED_BY_ID'] = [
			'TYPE' => Field::TYPE_INTEGER,
			'ATTRIBUTES' => [
				CCrmFieldInfoAttr::ReadOnly,
				CCrmFieldInfoAttr::AutoGenerated,
			],
		];

		return $info;
	}
}
