<?php

declare(strict_types=1);

namespace Bitrix\Main\DB\Ddl\Renderer;

use Bitrix\Main\DB\Ddl\Builder\AlterTableData;
use Bitrix\Main\DB\Ddl\Builder\CreateTableData;
use Bitrix\Main\DB\Ddl\Column\AbstractIntColumn;
use Bitrix\Main\DB\Ddl\Column\BigIntColumn;
use Bitrix\Main\DB\Ddl\Column\BlobColumn;
use Bitrix\Main\DB\Ddl\Column\BooleanColumn;
use Bitrix\Main\DB\Ddl\Column\CharColumn;
use Bitrix\Main\DB\Ddl\Column\ColumnInterface;
use Bitrix\Main\DB\Ddl\Column\ColumnParams;
use Bitrix\Main\DB\Ddl\Column\DateColumn;
use Bitrix\Main\DB\Ddl\Column\DateTimeColumn;
use Bitrix\Main\DB\Ddl\Column\DecimalColumn;
use Bitrix\Main\DB\Ddl\Column\DoubleColumn;
use Bitrix\Main\DB\Ddl\Column\FloatColumn;
use Bitrix\Main\DB\Ddl\Column\IntColumn;
use Bitrix\Main\DB\Ddl\Column\LongTextColumn;
use Bitrix\Main\DB\Ddl\Column\MediumIntColumn;
use Bitrix\Main\DB\Ddl\Column\MediumTextColumn;
use Bitrix\Main\DB\Ddl\Column\NumericColumn;
use Bitrix\Main\DB\Ddl\Column\SmallIntColumn;
use Bitrix\Main\DB\Ddl\Column\TextColumn;
use Bitrix\Main\DB\Ddl\Column\TimestampColumn;
use Bitrix\Main\DB\Ddl\Column\TinyIntColumn;
use Bitrix\Main\DB\Ddl\Column\TinyTextColumn;
use Bitrix\Main\DB\Ddl\Column\VarbinaryColumn;
use Bitrix\Main\DB\Ddl\Column\VarcharColumn;
use Bitrix\Main\DB\Ddl\Exception;
use Bitrix\Main\DB\Ddl\IndexColumn;

final class PgsqlRenderer implements RendererInterface
{
	private const LEFT_QUOTE = '"';
	private const RIGHT_QUOTE = '"';

	public function renderColumnDefinition(ColumnInterface $col): string
	{
		$params = $col->getParams();
		$type = $this->renderColumnType($col, $params);
		$autoIdentity = $col instanceof AbstractIntColumn && $params->isAutoincrement();

		$result = $this->quoteIdent($params->getName()) . ' ' . $type;

		if ($autoIdentity)
		{
			$result .= ' GENERATED BY DEFAULT AS IDENTITY';
		}

		if ($params->isNotNull())
		{
			$result .= ' NOT NULL';
		}

		if (!$autoIdentity)
		{
			$default = $params->getDefaultValue();
			if ($default !== null)
			{
				$result .= ' DEFAULT ' . $this->renderDefaultLiteral($col, $params, $default);
			}
			elseif ($col instanceof DateTimeColumn && $params->isCurrentTimestampAsDefault())
			{
				$result .= ' DEFAULT CURRENT_TIMESTAMP';
			}
		}

		return $result;
	}

	public function renderAlterColumnLines(ColumnInterface $col): array
	{
		$params = $col->getParams();
		$pgName = strtolower($params->getName());
		$type = $this->renderColumnType($col, $params);
		$lines = [];

		$lines[] = 'ALTER COLUMN "' . $pgName . '" TYPE ' . $type;

		$autoIdentity = $col instanceof AbstractIntColumn && $params->isAutoincrement();
		if ($autoIdentity)
		{
			$lines[] = 'ALTER COLUMN "' . $pgName . '" ADD GENERATED BY DEFAULT AS IDENTITY';
		}

		if ($params->isNotNull())
		{
			$lines[] = 'ALTER COLUMN "' . $pgName . '" SET NOT NULL';
		}
		else
		{
			$lines[] = 'ALTER COLUMN "' . $pgName . '" DROP NOT NULL';
		}

		if (!$autoIdentity)
		{
			$default = $params->getDefaultValue();
			if ($default !== null)
			{
				$lines[] = 'ALTER COLUMN "' . $pgName . '" SET DEFAULT ' . $this->renderDefaultLiteral($col, $params, $default);
			}
			elseif ($col instanceof DateTimeColumn && $params->isCurrentTimestampAsDefault())
			{
				$lines[] = 'ALTER COLUMN "' . $pgName . '" SET DEFAULT CURRENT_TIMESTAMP';
			}
			else
			{
				$lines[] = 'ALTER COLUMN "' . $pgName . '" DROP DEFAULT';
			}
		}

		return $lines;
	}

	public function renderCreateTable(CreateTableData $data): array
	{
		$queries = [];

		if (!empty($data->getColumns()))
		{
			$queries[] = $this->buildCreateTableQuery($data);
		}

		foreach ($data->getAddedIndexes() as $index)
		{
			$queries[] = $this->renderCreateIndex($index['type'], $data->getTableName(), $index['columns']);
		}

		return $queries;
	}

	public function renderAlterTable(AlterTableData $data): array
	{
		$alterLines = [];
		$queries = [];

		if ($data->isDropPrimaryKey())
		{
			$alterLines[] = 'DROP CONSTRAINT IF EXISTS "' . $data->getTableName() . '_pkey"';
		}

		foreach ($data->getDropIndexNames() as $name)
		{
			$queries[] = 'DROP INDEX IF EXISTS "' . $name . '"';
		}

		foreach ($data->getRenamedColumns() as $oldName => $newName)
		{
			$queries[] = 'ALTER TABLE "' . $data->getTableName() . '" RENAME COLUMN "'
				. strtolower($oldName) . '" TO "' . strtolower($newName) . '"';
		}

		foreach ($data->getDroppedColumns() as $name)
		{
			$alterLines[] = 'DROP COLUMN "' . strtolower($name) . '"';
		}

		foreach ($data->getAddedColumns() as $col)
		{
			$alterLines[] = 'ADD COLUMN ' . $this->renderColumnDefinition($col);
		}

		foreach ($data->getModifiedColumns() as $col)
		{
			array_push($alterLines, ...$this->renderAlterColumnLines($col));
		}

		$primaryKeys = $data->getPrimaryKeys();
		if (!empty($primaryKeys))
		{
			$keys = array_map(fn(string $key): string => $this->quoteIdent($key), $primaryKeys);
			$alterLines[] = 'ADD PRIMARY KEY (' . implode(', ', $keys) . ')';
		}

		if (!empty($alterLines))
		{
			$queries[] = 'ALTER TABLE "' . $data->getTableName() . '" ' . implode(', ', $alterLines);
		}

		foreach ($data->getAddedIndexes() as $index)
		{
			$queries[] = $this->renderCreateIndex($index['type'], $data->getTableName(), $index['columns']);
		}

		if (!empty($queries))
		{
			$queries[] = 'ANALYZE "' . $data->getTableName() . '"';
		}

		return $queries;
	}

	public function renderDropTable(string $tableName): string
	{
		return 'DROP TABLE IF EXISTS "' . $tableName . '"';
	}

	private function buildCreateTableQuery(CreateTableData $data): string
	{
		$lines = [];

		foreach ($data->getColumns() as $column)
		{
			$lines[] = "\t" . $this->renderColumnDefinition($column);
		}

		$primaryKeys = $data->getPrimaryKeys();
		if (!empty($primaryKeys))
		{
			$keys = array_map(fn(string $key): string => $this->quoteIdent($key), $primaryKeys);
			$lines[] = "\tPRIMARY KEY (" . implode(', ', $keys) . ')';
		}

		return 'CREATE TABLE "' . $data->getTableName() . '" (' . "\n"
			. implode(",\n", $lines) . "\n"
			. ')';
	}

	private function renderColumnType(ColumnInterface $col, ColumnParams $params): string
	{
		return match (true)
		{
			$col instanceof IntColumn => $params->isUnsigned() ? 'int8' : 'int',
			$col instanceof BigIntColumn => $params->isUnsigned() ? 'int8' : 'bigint',
			$col instanceof TinyIntColumn => $params->isUnsigned() ? 'int' : 'smallint',
			$col instanceof SmallIntColumn => $params->isUnsigned() ? 'int' : 'smallint',
			$col instanceof MediumIntColumn => $params->isUnsigned() ? 'int8' : 'int',
			$col instanceof BooleanColumn => 'smallint',
			$col instanceof DecimalColumn => 'decimal(' . $params->getMantissaLength() . ',' . $params->getExponentLength() . ')',
			$col instanceof NumericColumn => 'numeric(' . $params->getMantissaLength() . ',' . $params->getExponentLength() . ')',
			$col instanceof FloatColumn => 'real',
			$col instanceof DoubleColumn => 'double precision',
			$col instanceof VarcharColumn => 'varchar(' . $params->getLength() . ')',
			$col instanceof CharColumn => 'char(' . $params->getLength() . ')',
			$col instanceof VarbinaryColumn => 'bytea',
			$col instanceof TimestampColumn => 'timestamp',
			$col instanceof DateTimeColumn => 'timestamp',
			$col instanceof DateColumn => 'date',
			$col instanceof TinyTextColumn,
			$col instanceof MediumTextColumn,
			$col instanceof LongTextColumn,
			$col instanceof TextColumn => 'text',
			$col instanceof BlobColumn => 'bytea',
			default => throw new Exception(
				1200,
				'Unsupported column type',
				['class' => $col::class],
			),
		};
	}

	private function renderDefaultLiteral(ColumnInterface $col, ColumnParams $params, string $rawDefault): string
	{
		if ($col instanceof DateTimeColumn && $params->isCurrentTimestampAsDefault())
		{
			return 'CURRENT_TIMESTAMP';
		}
		return "'" . $rawDefault . "'";
	}

	private function quoteIdent(string $name): string
	{
		// PostgreSQL folds unquoted identifiers to lower case, and ORM always
		// references columns quoted-and-lower-cased. So DDL must
		// create/reference columns lower-cased too.
		return self::LEFT_QUOTE . strtolower($name) . self::RIGHT_QUOTE;
	}

	/**
	 * @param IndexColumn[] $columns
	 */
	private function renderCreateIndex(string $type, string $tableName, array $columns): string
	{
		$indexName = $this->buildIndexName($type, $tableName, $columns);

		if ($type === 'fulltext')
		{
			$tsvectors = array_map(
				static fn(IndexColumn $col): string => "to_tsvector('english', \"" . strtolower($col->getName()) . "\")",
				$columns,
			);

			return 'CREATE INDEX "' . $indexName
				. '" ON "' . $tableName
				. '" USING GIN (' . implode(' || ', $tsvectors) . ')';
		}

		$colDefs = array_map(
			function (IndexColumn $col): string {
				$line = '"' . strtolower($col->getName()) . '"';
				if ($col->sort !== null)
				{
					$line .= ' ' . strtoupper($col->sort);
				}
				return $line;
			},
			$columns,
		);
		$unique = $type === 'unique' ? 'UNIQUE ' : '';

		return 'CREATE ' . $unique . 'INDEX "' . $indexName
			. '" ON "' . $tableName . '" (' . implode(', ', $colDefs) . ')';
	}

	/**
	 * @param IndexColumn[] $columns
	 */
	private function buildIndexName(string $type, string $tableName, array $columns): string
	{
		$prefix = match ($type)
		{
			'unique' => 'ux_',
			'fulltext' => 'tx_',
			default => 'ix_',
		};

		$columnsStr = implode('_', array_map(
			static fn(IndexColumn $col): string => strtolower($col->getName()),
			$columns,
		));

		return substr($prefix . $tableName . '_' . $columnsStr, 0, 63);
	}
}
